### ISSUE TITLE
Hope you can change the picture of reademe.

### ISSUE THREAD

**Issue by yxt7979** [LyuLumos/CUC-ACM-OJ#2]
With too many grammatical mistakes, it really makes your introduction of the project fall in price.    

So, change it!    
 
![image-20210107183735017](https://littlefisher.oss-cn-beijing.aliyuncs.com/images/image-20210107183735017.png)

(I will never admit that I just want to try how to submit an Issue : D)

**Comment by LyuLumos** [comment]
This is just a sample image, frame is more important than content.
By the way, such a request like this should be made in [Discussions](https://github.com/LyuLumos/CUC-ACM-OJ/discussions)  instead of Issue.

**Comment by yxt7979** [comment]
..................



---Original---
